Ll/modification on modules
userlab-cesarsalazar/cabisa-web pull request #11
Opened 2021-05-04 08:12 UTC by userlab-luisdeleon

# Modificaciones en modulo inventario

[TICKET](https://app.asana.com/0/1200273810661299/1200273810661331/f)
- [X] QA @userlab-luisdeleon 
- [ ] CR @userlab-cesarsalazar 

## What changed?

- Se cambiaron visualmente los botones de las tablas que ejecutan alguna accion sobre la informacion

![image](https://user-images.githubusercontent.com/59143067/116975138-637d2480-ac7c-11eb-91d2-d437f0a2d07d.png) ![image](https://user-images.githubusercontent.com/59143067/116975157-6d9f2300-ac7c-11eb-92d9-23cf92fe49e7.png)

- Se separaron los modulos en Servicios y productos

![image](https://user-images.githubusercontent.com/59143067/116974999-29ac1e00-ac7c-11eb-88c2-cb2c62fa220e.png)

- Se agrego el modulo movimiento de inventarios

![image](https://user-images.githubusercontent.com/59143067/116974840-f5d0f880-ac7b-11eb-99ef-1834f8cdebda.png)

2021-05-04 14:58 UTC, userlab-cesarsalazar commented
¿Puedes hacer ese Menu de tipo acordeon @userlab-luisdeleon ?

2021-05-06 02:22 UTC, userlab-luisdeleon commented
@userlab-cesarsalazar  Listo, se cambio por menu tipo acordeon

![image](https://user-images.githubusercontent.com/59143067/117233053-9f7cca80-addf-11eb-8d8a-abee8a35c556.png)

2021-05-06 15:01 UTC, userlab-cesarsalazar commented
@userlab-luisdeleon perfecto gracias

2021-05-06 15:04 UTC, userlab-cesarsalazar requested changes

2021-05-06 15:04 UTC, userlab-cesarsalazar commented on src/components/Menu.js
> +            style={{color: 'var(--cabisa-yellow)', fontSize: '18px'}}
crea una clase para esto, no es buena practica duplicar tanto codigo

2021-05-06 15:04 UTC, userlab-cesarsalazar commented on src/components/Menu.js
> +            style={{color: 'var(--cabisa-yellow)', fontSize: '18px'}}
crea una clase para esto, no es buena practica duplicar tanto codigo

2021-05-06 15:04 UTC, userlab-cesarsalazar commented on src/components/Menu.js
> +            style={{color: 'var(--cabisa-yellow)', fontSize: '18px'}}
crea una clase para todo esto

2021-05-06 15:04 UTC, userlab-cesarsalazar commented on src/components/Menu.js
> +      style={{height: '100%', paddingTop: '5px', border: 'none', overflowY: 'auto', paddingBottom: '75px' }}
calse

2021-05-06 15:04 UTC, userlab-cesarsalazar commented on src/components/Menu.js
> +
remover codigo innecesario

2021-05-06 15:04 UTC, userlab-cesarsalazar commented on src/components/Menu_routes.js
> +      /^(\/inventoryMovements)|(\/InventoryMovementsView)|(\/inventoryProducts)|(\/inventoryServices)|(\/inventoryProductsView)|(\/inventoryServicesView)/i,
¿que es esto?

2021-05-06 15:04 UTC, userlab-cesarsalazar commented on src/components/Menu_routes.js
> +  // {
remover codigo innecesario

2021-05-06 17:36 UTC, userlab-luisdeleon commented on src/components/Menu_routes.js
> +      /^(\/inventoryMovements)|(\/InventoryMovementsView)|(\/inventoryProducts)|(\/inventoryServices)|(\/inventoryProductsView)|(\/inventoryServicesView)/i,
esto sirve para que al momento de recargar la pagina no se pierda en el menu en que sección estas estas ubicado

![image](https://user-images.githubusercontent.com/59143067/117341354-3dfc4080-ae5f-11eb-8530-ce662af27dc4.png)

2021-05-06 17:59 UTC, userlab-cesarsalazar approved these changes

2021-05-06 17:59 UTC, merged